favicon: null
name: Exinus Events
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.6003584
  brandStrength: 0.8387097
  lightness: 0.3763441
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#BDBDBD'
    - '#E0E0E0'
    - '#3F3F3F'
  rhythmicContrast: 0.8154122
typography_spectrum: 0.827957
layout_spectrum: 0.9731183
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
