name: Exinus Events
favicon: null
layout_spectrum: 0.612474367255345
typography_spectrum: 0.46116859070025384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6049709802027792
  lightness: 0.5305155462119728
  saturation: 0.5375792488921434
  rhythmicContrast: 0.1940208929590881
purpose: []
